// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD7M5YEBjcFriHHBa4hz22vVLYWqHhhwY',
    appId: '1:682325687146:web:7c409a47826a29d68e4313',
    messagingSenderId: '682325687146',
    projectId: 'mini-wallet-b8198',
    authDomain: 'mini-wallet-b8198.firebaseapp.com',
    storageBucket: 'mini-wallet-b8198.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSFj6_YphujqdtX4LjqXdaofvjIjpSVc4',
    appId: '1:682325687146:android:be3f66da11e18d7d8e4313',
    messagingSenderId: '682325687146',
    projectId: 'mini-wallet-b8198',
    storageBucket: 'mini-wallet-b8198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0m8N9dYCczWD_Sm6Iei01EWVQ9uchu7o',
    appId: '1:682325687146:ios:bd4473fc522df79b8e4313',
    messagingSenderId: '682325687146',
    projectId: 'mini-wallet-b8198',
    storageBucket: 'mini-wallet-b8198.appspot.com',
    iosBundleId: 'com.miniwallet.miniWallet',
  );
}
